### ISSUE TITLE
RFC: Spryks

### ISSUE THREAD

**Issue by dereuromark** [spryker/spryk#6]
recommendation:

Name "Spryks" here?

**Comment by stereomon** [comment]
Where exactly? The repo name?

**Comment by dereuromark** [comment]
Yes.
It makes it a bit more clear and less looking like a typo :)
No big deal either way.

**Comment by stereomon** [comment]
I would not rename it to spryk. We use spryk as singular and spryks as plural as we do for other module names as well. But we can discuss this shortly with our team to find a naming we all agree on.

**Comment by stereomon** [comment]
We discussed the renaming and we decided to keep the singular name as it is.

**Comment by dereuromark** [comment]
This is a collection not feature name. 
I strongly recommend the rename.
